version: '2'
services:
  fbctf:
   image: fbctf_in_dev
   restart: always
   container_name: fbctf 
   environment:
   - VIRTUAL_HOST=platform.superctf.io
   - VIRTUAL_PORT=443
   network_mode: "bridge"
  
  chall1:
   image: php:7.0-apache 
   container_name: chall1
   links:
   - chall1mysql
   environment:
   - VIRTUAL_HOST=chall1.superctf.io
   - VIRTUAL_PORT=80
   network_mode: "bridge"

  chall1mysql:
   image: mysql:5.6
   environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=test
   container_name: mysql
   network_mode: "bridge"
 
  doc:
    image: ghost
    restart: always
    environment:
    - VIRTUAL_HOST=doc.superctf.io
    - VIRTUAL_PORT=2368
    volumes:
    - ./blog:/var/lib/ghost
    container_name: doc
    network_mode: "bridge"

  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    ports:
    - "80:80"
    - "443:443"
    environment:
    - VIRTUAL_HOST=superctf.io
    volumes:
    - ./nginx-proxy/certs/:/etc/nginx/certs
    - /var/run/docker.sock:/tmp/docker.sock:ro
    container_name: nginx-proxy
    network_mode: "bridge"
