version: '2'

services:
  fbctf:
   image: alexgaspar/fbctf:latest
   restart: always
   container_name: fbctf
   environment:
   - VIRTUAL_HOST=platform.superctf.io
   - VIRTUAL_PORT=443
   - VIRTUAL_PROTO=HTTPS
   - MYSQL_USER=fbctf
   - MYSQL_PASSWORD=fbctf
   - MYSQL_DATABASE=fbctf
   - MYSQL_PORT=3306
   links:
   - mysql-fbctf:mysql
   networks:
     - platform

  mysql-fbctf:
   image: mysql:5.6
   environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=fbctf
   - MYSQL_USER=fbctf
   - MYSQL_PASSWORD=fbctf
   container_name: mysql-fbctf
   networks:
     - platform

  # doc:
  #   image: ghost
  #   restart: always
  #   environment:
  #   - VIRTUAL_HOST=doc.superctf.io
  #   - VIRTUAL_PORT=2368
  #   volumes:
  #   - ./blog:/var/lib/ghost
  #   container_name: doc
  #   network_mode: "bridge"

  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    ports:
    - "80:80"
    - "443:443"
    environment:
    - VIRTUAL_HOST=superctf.io
    volumes:
    - ./nginx-proxy/certs/:/etc/nginx/certs
    - /var/run/docker.sock:/tmp/docker.sock:ro
    container_name: nginx-proxy
    networks:
      - platform
      - chall

networks:
  platform:
  chall:

    # config:
    #   -subnet: 172.18.0.0/16
    #   ip_range: 172.18.0.0/16
    #   gateway: 172.18.0.1
