version: '2'
services:
  db:
    image: postgres:9.3
    container_name: "db"
    network_mode: "bridge"

  msf:
    build:
      context: .
    image: msf
    ports:
      - 4444:4444
    links:
    - db
    container_name: "msf"
    network_mode: "bridge"
